### ISSUE TITLE
Image pull URLs need to be https

### ISSUE THREAD

**Issue by SomewhatDamaged** [Alzarath/Booru-Cogs#6]
Affects pony.py not sure about the others.

Someone already helped me find this out, and said they let you know about it, but figured I would make it official and pop it in the tracker.

The two lines:

return await self.bot.edit_message(message, "http:{}".format(website["image"]))

and

return await self.bot.edit_message(message, "http:{}".format(website["search"][0]["image"]))

Need to be https requests, for Discord to show the resultant images as previews. 

Could turn this into a feature, too. Use it as a way to "hide previews of explicit images" when an option is set.

**Comment by Alzarath** [comment]
Ah, so that's why I was having issues. Think someone mentioned it to me but I forgot to fix it. Fixed in 31f5cb2.

If I were to add that, I'd do it in a more reliable way by simply adding `<` and `>` around the link. It'd be more of an issue of what circumstances that should be applied to a link. I think server admins being able to broadly disable embedding for the bot is adequate. If you want to try your hand at adding it yourself, feel free to throw in a pull request.
